newsaggregator/core/urls.py
from django.urls import path
from core import views
# from .views import base_view
from .views import fetch_article_content

from .views import news_list

app_name='core'

    

urlpatterns=[
    # path('base/', base_view, name='base'),
    path('',views.news_list,name='index'),
    path('about/', views.about, name='about'),
    path('contact/',views.contact,name='contact'),
   
    path('advertise/',views.advertise,name='advertise'),
    path('privacy/',views.privacy,name='privacy'),
    path('scrape/<str:name>', views.scrape, name="scrape"),
    
        # bookmarking
    path('bookmarks/', views.view_bookmarks, name='view_bookmarks'),

    path('remove_bookmark/<int:headline_id>/', views.remove_bookmark, name='remove_bookmark'),
    path('rate_headline/<int:headline_id>/', views.rate_headline, name='rate_headline'),
    path('top-rated/', views.top_rated_articles, name='top_rated_articles'),

    path('fetch_article_content/', fetch_article_content, name='fetch_article_content'),

]

newsaggregator/newsaggregator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from userauths import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userauths.urls')),
    path('',include('core.urls')),
    path('login/',views.login, name ='login'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    path('social-auth/',include('social_django.urls',namespace='social')),
    path("",views.home,name='home'),

    
]

newsaggregator/userauths/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from userauths import views

app_name='userauths'

urlpatterns=[
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('sign-out/',views.logout_view,name='sign-out'),
]

newsaggregator/userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    # Add related_name to avoid clashes with auth.User
    groups = models.ManyToManyField(
        "auth.Group",
        related_name="userauths_user_set",
        blank=True,
        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
        verbose_name="groups",
    )
    
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="userauths_user_set",
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    def __str__(self):
        return self.username
    

newsaggregator/userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.core.exceptions import ValidationError


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 6:
            raise ValidationError("Username must be at least 6 characters long.")
        return username

newsaggregator/userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import logout

User=settings.AUTH_USER_MODEL

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, your account was created successfully")

            new_user = authenticate(username=form.cleaned_data['email'], 
                                    password=form.cleaned_data['password1'])
            
            login(request, new_user)
            return redirect("core:index")
    else:
        form=UserRegisterForm()

    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)

def login_view(request):
    
    if request.user.is_authenticated:
        messages.warning(request,f"Hey, You are already Logged in")
        return redirect('core:index')
    else:
        if request.method=="POST":
            email=request.POST.get("email")
            password=request.POST.get("password")

            try:
                user=User.object.get(email=email)
            except:
                messages.warning(request,f"User with {email} does not exist")
                

            user=authenticate(request,email=email,password=password)

            if user is not None:
                login(request,user)             
                return redirect("core:index")
            
            else:
                messages.warning(request,"User Does not exist, create an account")
                
    return render(request,"userauths/sign-in.html")


def logout_view(request):
   
    logout(request)
    messages.success(request, "You Logged-Out, successfully")
    
    return redirect("userauths:sign-in",)

def home(request):
    return render(request,'base_auth.html')

newsaggregator/templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}

{% block authentication %}
<style>
    .social-container1 {
        text-align: center; /* Center-align content */
    }

    .btn-primary1 {
        background-color: #4285F4; /* Google Blue */
        border: none; /* Remove border */
        padding: 10px 20px; /* Adjust padding */
        font-size: 16px; /* Adjust font size */
        cursor: pointer; /* Add cursor pointer on hover */
    }

    .btn-primary1:hover {
        background-color: #357AE8; /* Darker shade of Google Blue on hover */
    }

    .btn-lin {
        color: #fff; /* White text color */
        text-decoration: none; /* Remove underline */
    }

    .btn-lin:hover {
        color: #fff; /* White text color on hover */
        text-decoration: none; /* Remove underline on hover */
    }
</style>

<div class="container">
    <div class="main-container">
        <div class="main-content">
            <div class="row">
                <div class="col-md-6">
                    <img src="../../static/assets/images/sign-in-animate.svg" style="width: max-content;">
                </div>
                <div class="col-md-6" style="display: flex;align-items: center;justify-content: center;">
                    <div class="form-container">
                        <div class="form-content box">
                            <div class="logo">
                                <img src="../../static/assets/images/news.png" width="80px" alt="News logo" class="logo-light">
                                <img src="../../static/assets/images/news.png" width="80px" alt="News logo" class="logo-dark">
                            </div>
                            
                            {% for message in messages %}
                            {% if message.level == "success" %}
                              <div class="alert alert-success">
                                {{ message }}
                              </div>
                                                        
                            {% else %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                              </div>
                            {% endif %}
                          {% endfor %}
                          

                            
                            <form method="POST">
                                {% csrf_token %}
                                <div class="signin-form" id="signin-form">
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter email
                                            </span>
                                            <input class="login-signup-input" type="text" name="email" maxlength="100" required="" id="login_username">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter Password
                                            </span>
                                            <input class="login-signup-input" type="password" name="password" autocomplete="current-password" required="" id="login_password">
                                            <button>Show</button>
                                        </div>
                                    </div>
                                    <div class="btn-groupss">
                                        <button class="btn-login" id="signin-btn" type="submit">
                                            Sign In
                                        </button>
                                    </div>
                                </div>
                            </form>
                            
                            <div class="row">
                                <div class="col-md-8 mx-auto my-2 order-md-1">
                                    <div class="social-container1">
                                        <button class="btn btn-primary1 mb-4">
                                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn-lin">Login With Google</a>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            
                       
                        </div>
                        <div class="box goto">
                            <p>
                                <span style="color: var(--foreground-tertiary);">Don't have an account?</span>
                                <a href="{% url 'userauths:sign-up' %}">Sign up</a>
                            </p>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock authentication %}

newsaggregator/templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}

{% block authentication %}

<style>
    .social-container1 {
        text-align: center; /* Center-align content */
    }

    .btn-primary1 {
        background-color: #4285F4; /* Google Blue */
        border: none; /* Remove border */
        padding: 10px 20px; /* Adjust padding */
        font-size: 16px; /* Adjust font size */
        cursor: pointer; /* Add cursor pointer on hover */
    }

    .btn-primary1:hover {
        background-color: #357AE8; /* Darker shade of Google Blue on hover */
    }

    .btn-lin {
        color: #fff; /* White text color */
        text-decoration: none; /* Remove underline */
    }

    .btn-lin:hover {
        color: #fff; /* White text color on hover */
        text-decoration: none; /* Remove underline on hover */
    }
</style>
<div class="container">
    <div class="main-container">
        <div class="main-content">
            <div class="row">
                <div class="col-md-6">
                    <img src="../../static/assets/images/sign-up-animate.svg" style="width: max-content;">
                </div>
                <div class="col-md-6" style="display: flex;align-items: center;justify-content: center;">
                    <div class="form-container">
                        <div class="form-content box">
                            <div class="logo">
                                <img src="../../static/assets/images/news.png" width="80px" alt="News logo" class="logo-light">
                                <img src="../../static/assets/images/news.png" width="80px" alt="News logo" class="logo-dark">
                            </div>

                            {% if form.errors %}
                            <div class="errors">
                                <ul>
                                    {% for field, error_list in form.errors.items %}
                                        {% for error in error_list %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                                <p>Please try again</p>
                            </div>
                        {% endif %}
        
        
                            <form method="POST">
                                {% csrf_token %}
                                <div class="signin-form" id="signin-form">
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter Username
                                            </span>
                                            <input class="login-signup-input" type="text" name="username" maxlength="100" required id="id_username">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter email
                                            </span>
                                            <input class="login-signup-input" type="email" name="email" maxlength="320" required id="id_email">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter Password
                                            </span>
                                            <input class="login-signup-input" type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1">
                                            <button type="button">Show</button>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="animate-input">
                                            <span>
                                                Enter confirm Password
                                            </span>
                                            <input class="login-signup-input" type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2">
                                            <button type="button">Show</button>
                                        </div>
                                    </div>
                                    <div class="password-requirements">
                                        <ul>
                                            <li>Username must be atleast 6 characters long</li>
                                            <li>Password must be at least 8 characters long</li>
                                            <li>Password shouldn't be very similar to the username</li>
                                            <li>Password shouldn't be entirely numeric</li>
                                        </ul>
                                    </div>
                                    <div class="btn-groupss">
                                        <button class="btn-login" id="signin-btn" type="submit">
                                            Sign Up
                                        </button>
                                    </div>
                                    
                                    
                                </div>
                            </form>
                            <div class="row">
                                <div class="col-md-8 mx-auto my-2 order-md-1">
                                    <div class="social-container1">
                                        <button class="btn btn-primary1 mb-4">
                                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn-lin">Login With Google</a>
                                        </button>
                                    </div>
                                </div>
                            </div>
        
                        </div>
                        <div class="box goto">
                            <p>
                                <span style="color: var(--foreground-tertiary);">have an account?</span>
                                <a href="{% url 'userauths:sign-in' %}">Sign in</a>
                            </p>
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock authentication %}