newsaggregator/core/urls.py
from django.urls import path
from core import views
# from .views import base_view
from .views import fetch_article_content

from .views import news_list

app_name='core'

    

urlpatterns=[
    # path('base/', base_view, name='base'),
    path('',views.news_list,name='index'),
    path('about/', views.about, name='about'),
    path('contact/',views.contact,name='contact'),
   
    path('advertise/',views.advertise,name='advertise'),
    path('privacy/',views.privacy,name='privacy'),
    path('scrape/<str:name>', views.scrape, name="scrape"),
    
        # bookmarking
    path('bookmarks/', views.view_bookmarks, name='view_bookmarks'),

    path('remove_bookmark/<int:headline_id>/', views.remove_bookmark, name='remove_bookmark'),
    path('rate_headline/<int:headline_id>/', views.rate_headline, name='rate_headline'),
    path('top-rated/', views.top_rated_articles, name='top_rated_articles'),

    path('fetch_article_content/', fetch_article_content, name='fetch_article_content'),

]

newsaggregator/newsaggregator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from userauths import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('userauths.urls')),
    path('',include('core.urls')),
    path('login/',views.login, name ='login'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    path('social-auth/',include('social_django.urls',namespace='social')),
    path("",views.home,name='home'),

    
]

newsaggregator/userauths/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from userauths import views

app_name='userauths'

urlpatterns=[
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('sign-out/',views.logout_view,name='sign-out'),
]

newsaggregator/news/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

newsaggregator/templates/components/category-btn.html
<div style="display: flex; align-items: center; justify-content: flex-end;">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Category
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='latest' %}">Latest</a></li>
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='entertainment' %}">Entertainment</a></li>
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='sports' %}">Sports</a></li>
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='politics' %}">Politics</a></li>
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='opinion' %}">Opinion</a></li>
            <li><a class="dropdown-item" href="{% url 'core:scrape' name='breaking-news' %}">Breaking News</a></li>
            <li><a class="dropdown-item" href="{% url 'core:top_rated_articles' %}">Top Rated</a></li>

        </ul>
    </div>
</div>

newsaggregator/templates/components/email.html
<h1 style="color: #a0aec0;">Onion Contact Form Submission</h1>

<p><b>Name:</b> {{ name }}</p>
<p><b>Email:</b> {{ email }}</p>
<p><b>Email:</b> {{ phone }}</p>
<p><b>Message:</b> {{ content }}</p>

<p style="color: #7f8c8d;">This email is generated from the Onion contact form.</p>

<hr style="border: 1px solid #bdc3c7; margin-top: 20px;">

<p style="color: #7f8c8d;">&copy; 2024 Onion News. All rights reserved.</p>

newsaggregator/templates/components/footer.html
{% load static %}
<footer class="container">
    <div class="footer-section row" style="justify-content: space-between;">
        <div class="wrapper col-md-3 col-12">
            <a href="#" class="footer-logo">
                <span class="logo-light">
                    <span class="logo-container"><img src="{% static './assets/images/news.png' %}" alt="logo" width="70" />Onion News</span>
                </span>
                <span class="logo-dark">
                    <span class="logo-container"><img src="{% static './assets/images/news.png' %}" alt="logo" width="70" />Onion News</span>
                </span>
            </a>

            <p class="footer-text">
                <span>&copy; <script>document.write(new Date().getFullYear())</script> Onion News Aggregator. All rights reserved.</span>
            </p>
        </div>

        <div class="wrapper col-md-3 col-12" style="justify-content: center;display: flex;">
            <div id="google_element"></div>
            <script src="https://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate"></script>
            <script>
              function loadGoogleTranslate() {
                new google.translate.TranslateElement({
                  pageLanguage: 'en'
                }, 'google_element');
              }
            </script>
        </div>

        <div class="wrapper col-md-3 col-12" style="display: flex;justify-content: space-around;flex-direction: column;">
            <p class="footer-title">Legal Stuff</p>
            <ul>
                <li>
                    <a href="{% url 'core:privacy' %}" class="footer-link">Privacy Notice</a>
                </li>
                <li>
                    <a href="#" style="pointer-events: none; opacity: 0.5;" class="footer-link">Cookie Policy</a>
                </li>
                <li>
                    <a href="#" style="pointer-events: none; opacity: 0.5;" class="footer-link">Terms Of Use</a>
                </li>
            </ul>
        </div>
    </div>

    <p class="copyright" style="margin: 0;">&copy; Copyright 2024 <a href="#">Onion News</a></p>
</footer>

newsaggregator/templates/components/navbar.html
{% load static %}
<nav class="navbar">
    <a href="{% url 'core:index' %}">
        <span class="logo-light">
            <span class="logo-container"><img src="{% static './assets/images/news.png' %}" alt="logo"
                    width="70" />Onion News</span>
        </span>
        <span class="logo-dark">
            <span class="logo-container"><img src="{% static './assets/images/news.png' %}" alt="logo"
                    width="70" />Onion News</span>
        </span>
    </a>
    <div class="btn-group">
        <button class="theme-btn theme-btn-mobile light">
            <ion-icon name="moon" class="moon"></ion-icon>
            <ion-icon name="sunny" class="sun"></ion-icon>
        </button>

        <button class="nav-menu-btn">
            <ion-icon name="menu-outline"></ion-icon>
        </button>
    </div>

    <div class="flex-wrapper">
        <ul class="desktop-nav">
            <!-- Start of list item for Home link -->
            <li {% if not request.user.is_authenticated %} style="pointer-events: none;" {% endif %}>
                <!-- Link to the Home page. The URL is generated using Django's url template tag, which takes the name of a view function or a URL pattern name. -->
                <a {% if request.user.is_authenticated %} href="{% url 'core:index' %}" {% endif %} class="nav-link">Home</a>
            </li>

            <!-- Start of list item for My Bookmarks link -->
            <li {% if not request.user.is_authenticated %} style="pointer-events: none;" {% endif %}>
                <!-- Link to the My Bookmarks page. The URL is generated using Django's url template tag. -->
                <a {% if request.user.is_authenticated %} href="{% url 'core:view_bookmarks' %}" {% endif %} class="nav-link">My Bookmarks</a>
            </li>

            <!-- Start of list item for About Us link -->
            <li>
                <!-- Link to the About Us page. The URL is generated using Django's url template tag. -->
                <a href="{% url 'core:about' %}" class="nav-link">About Us</a>
            </li>

            <!-- Start of list item for Contact link -->
            <li>
                <!-- Link to the Contact page. The URL is generated using Django's url template tag. -->
                <a href="{% url 'core:contact' %}" class="nav-link">Contact</a>
            </li>
            <li>
                {% if not request.user.is_authenticated %}
                <a href="{% url 'userauths:sign-up' %}" class="nav-link">Sign-in/Sign-up</a>
                {% else %}
                <a href="{% url 'userauths:sign-out' %}" class="nav-link">Sign-out</a>
                {% endif %}
            </li>
        </ul>

        <button class="theme-btn theme-btn-desktop light">
            <ion-icon name="moon" class="moon"></ion-icon>
            <ion-icon name="sunny" class="sun"></ion-icon>
        </button>
    </div>

    <div class="mobile-nav">
        <button class="nav-close-btn">
            <ion-icon name="close-outline"></ion-icon>
        </button>

        <div class="wrapper">
            <p class="h3 nav-title">Main Menu</p>

            <ul>
                <li class="nav-item">
                    <a href="{% url 'core:index' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:view_bookmarks' %}" class="nav-link">My Bookmarks</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'core:about' %}" class="nav-link">About Me</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'core:contact' %}" class="nav-link">Contact</a>
                </li>
            </ul>
        </div>

        <div>
            <p class="h3 nav-title">Topics</p>

            <ul>
                <li class="nav-item">
                    <a href="#" class="nav-link">Web Develop</a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">AI/ML</a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">Data Science</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

newsaggregator/templates/components/swiperjs.html
{% load static %}
<!-- Link Swiper's CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

<!-- swiper styles -->
<style>
    .swiper {
        width: 100%;
        height: 100%;
        padding: 10px;
    }

    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: transparent;
    }

    .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
        border-radius: 10px;

    }
    .swiper-image{
        position: relative;
        overflow: hidden;

    }
    .swiper-bottom{
        position: absolute;
        bottom: 0;
    }
</style>

<!-- Swiper -->
<div class="swiper mySwiper">
    <div class="swiper-wrapper">
        <!--{% for record in object_list %}-->
        <div class="col-12 col-md-6 col-lg-4 mb-4 newscard swiper-slide">
            <div class="row">
                <div class="col-md-12 swiper-image">
                    <img style="max-height: 20em;" class="card-img-top" src="{{ record.image }}" alt="News Image" loading="lazy">
                    <div class="col-md-12 swiper-bottom">
                        <div class="card-body d-flex" style="justify-content: center;">
                            <span class="card-title" style="text-align: left;background-color: aliceblue;padding: 1px 5px;">
                                <a style="color: var(--accent)!important;" href="#" class="news-link text-dark" data-toggle="modal" data-target="#newsModal"
                                    data-url="{{ record.url }}">{{ record.title }}</a>
                            </span>
                        </div>    
                    </div>
                </div>

            </div>
        </div>
        <!--{% endfor %}-->
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
</div>

<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper(".mySwiper", {
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: {
            delay: 2500,
            disableOnInteraction: false,
        },
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
    });
</script>